# This file is used to start all frontend services
services:

  # Flight Tracker Event App (User Interface)
  flight-tracker-event-app:
    build:
      context: ./flight-tracker-event-app
      dockerfile: Dockerfile
      args:
        - WEBSOCKET_URL=${FLIGHT_TRACKER_EVENT_APP_WEBSOCKET_URL}
        - WEBSOCKET_RECONNECT_INTERVAL=${FLIGHT_TRACKER_EVENT_APP_WEBSOCKET_RECONNECT_INTERVAL}
        - WEBSOCKET_MAX_RETRIES=${FLIGHT_TRACKER_EVENT_APP_WEBSOCKET_MAX_RETRIES}
        - GOOGLE_MAPS_API_KEY=${FLIGHT_TRACKER_EVENT_APP_GOOGLE_MAPS_API_KEY}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - WEBSOCKET_URL=${FLIGHT_TRACKER_EVENT_APP_WEBSOCKET_URL}
      - WEBSOCKET_RECONNECT_INTERVAL=${FLIGHT_TRACKER_EVENT_APP_WEBSOCKET_RECONNECT_INTERVAL}
      - WEBSOCKET_MAX_RETRIES=${FLIGHT_TRACKER_EVENT_APP_WEBSOCKET_MAX_RETRIES}
      - GOOGLE_MAPS_API_KEY=${FLIGHT_TRACKER_EVENT_APP_GOOGLE_MAPS_API_KEY}
    volumes:
      - flight-tracker-event-app-logs:/var/log
    networks:
      - flight-tracker-network
    depends_on:
      - flight-tracker-event-server
    restart: unless-stopped

volumes:
  flight-tracker-event-app-logs:
